/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugeRouteImport } from './routes/usluge'
import { Route as RepertoarRouteImport } from './routes/repertoar'
import { Route as NacinRadaRouteImport } from './routes/nacin-rada'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as HvalaRouteImport } from './routes/hvala'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DostupniTerminiRouteImport } from './routes/dostupni-termini'
import { Route as DopunskiProgramiRouteImport } from './routes/dopunski-programi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpitSvadbaRouteImport } from './routes/upit.svadba'
import { Route as UpitRodjendanJubilejRouteImport } from './routes/upit.rodjendan-jubilej'
import { Route as UpitKorporativnaProslavaRouteImport } from './routes/upit.korporativna-proslava'
import { Route as UpitKlupskaSvirkaRouteImport } from './routes/upit.klupska-svirka'

const UslugeRoute = UslugeRouteImport.update({
  id: '/usluge',
  path: '/usluge',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertoarRoute = RepertoarRouteImport.update({
  id: '/repertoar',
  path: '/repertoar',
  getParentRoute: () => rootRouteImport,
} as any)
const NacinRadaRoute = NacinRadaRouteImport.update({
  id: '/nacin-rada',
  path: '/nacin-rada',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const HvalaRoute = HvalaRouteImport.update({
  id: '/hvala',
  path: '/hvala',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DostupniTerminiRoute = DostupniTerminiRouteImport.update({
  id: '/dostupni-termini',
  path: '/dostupni-termini',
  getParentRoute: () => rootRouteImport,
} as any)
const DopunskiProgramiRoute = DopunskiProgramiRouteImport.update({
  id: '/dopunski-programi',
  path: '/dopunski-programi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpitSvadbaRoute = UpitSvadbaRouteImport.update({
  id: '/upit/svadba',
  path: '/upit/svadba',
  getParentRoute: () => rootRouteImport,
} as any)
const UpitRodjendanJubilejRoute = UpitRodjendanJubilejRouteImport.update({
  id: '/upit/rodjendan-jubilej',
  path: '/upit/rodjendan-jubilej',
  getParentRoute: () => rootRouteImport,
} as any)
const UpitKorporativnaProslavaRoute =
  UpitKorporativnaProslavaRouteImport.update({
    id: '/upit/korporativna-proslava',
    path: '/upit/korporativna-proslava',
    getParentRoute: () => rootRouteImport,
  } as any)
const UpitKlupskaSvirkaRoute = UpitKlupskaSvirkaRouteImport.update({
  id: '/upit/klupska-svirka',
  path: '/upit/klupska-svirka',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dopunski-programi': typeof DopunskiProgramiRoute
  '/dostupni-termini': typeof DostupniTerminiRoute
  '/faq': typeof FaqRoute
  '/hvala': typeof HvalaRoute
  '/instagram': typeof InstagramRoute
  '/kontakt': typeof KontaktRoute
  '/nacin-rada': typeof NacinRadaRoute
  '/repertoar': typeof RepertoarRoute
  '/usluge': typeof UslugeRoute
  '/upit/klupska-svirka': typeof UpitKlupskaSvirkaRoute
  '/upit/korporativna-proslava': typeof UpitKorporativnaProslavaRoute
  '/upit/rodjendan-jubilej': typeof UpitRodjendanJubilejRoute
  '/upit/svadba': typeof UpitSvadbaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dopunski-programi': typeof DopunskiProgramiRoute
  '/dostupni-termini': typeof DostupniTerminiRoute
  '/faq': typeof FaqRoute
  '/hvala': typeof HvalaRoute
  '/instagram': typeof InstagramRoute
  '/kontakt': typeof KontaktRoute
  '/nacin-rada': typeof NacinRadaRoute
  '/repertoar': typeof RepertoarRoute
  '/usluge': typeof UslugeRoute
  '/upit/klupska-svirka': typeof UpitKlupskaSvirkaRoute
  '/upit/korporativna-proslava': typeof UpitKorporativnaProslavaRoute
  '/upit/rodjendan-jubilej': typeof UpitRodjendanJubilejRoute
  '/upit/svadba': typeof UpitSvadbaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dopunski-programi': typeof DopunskiProgramiRoute
  '/dostupni-termini': typeof DostupniTerminiRoute
  '/faq': typeof FaqRoute
  '/hvala': typeof HvalaRoute
  '/instagram': typeof InstagramRoute
  '/kontakt': typeof KontaktRoute
  '/nacin-rada': typeof NacinRadaRoute
  '/repertoar': typeof RepertoarRoute
  '/usluge': typeof UslugeRoute
  '/upit/klupska-svirka': typeof UpitKlupskaSvirkaRoute
  '/upit/korporativna-proslava': typeof UpitKorporativnaProslavaRoute
  '/upit/rodjendan-jubilej': typeof UpitRodjendanJubilejRoute
  '/upit/svadba': typeof UpitSvadbaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dopunski-programi'
    | '/dostupni-termini'
    | '/faq'
    | '/hvala'
    | '/instagram'
    | '/kontakt'
    | '/nacin-rada'
    | '/repertoar'
    | '/usluge'
    | '/upit/klupska-svirka'
    | '/upit/korporativna-proslava'
    | '/upit/rodjendan-jubilej'
    | '/upit/svadba'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dopunski-programi'
    | '/dostupni-termini'
    | '/faq'
    | '/hvala'
    | '/instagram'
    | '/kontakt'
    | '/nacin-rada'
    | '/repertoar'
    | '/usluge'
    | '/upit/klupska-svirka'
    | '/upit/korporativna-proslava'
    | '/upit/rodjendan-jubilej'
    | '/upit/svadba'
  id:
    | '__root__'
    | '/'
    | '/dopunski-programi'
    | '/dostupni-termini'
    | '/faq'
    | '/hvala'
    | '/instagram'
    | '/kontakt'
    | '/nacin-rada'
    | '/repertoar'
    | '/usluge'
    | '/upit/klupska-svirka'
    | '/upit/korporativna-proslava'
    | '/upit/rodjendan-jubilej'
    | '/upit/svadba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DopunskiProgramiRoute: typeof DopunskiProgramiRoute
  DostupniTerminiRoute: typeof DostupniTerminiRoute
  FaqRoute: typeof FaqRoute
  HvalaRoute: typeof HvalaRoute
  InstagramRoute: typeof InstagramRoute
  KontaktRoute: typeof KontaktRoute
  NacinRadaRoute: typeof NacinRadaRoute
  RepertoarRoute: typeof RepertoarRoute
  UslugeRoute: typeof UslugeRoute
  UpitKlupskaSvirkaRoute: typeof UpitKlupskaSvirkaRoute
  UpitKorporativnaProslavaRoute: typeof UpitKorporativnaProslavaRoute
  UpitRodjendanJubilejRoute: typeof UpitRodjendanJubilejRoute
  UpitSvadbaRoute: typeof UpitSvadbaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usluge': {
      id: '/usluge'
      path: '/usluge'
      fullPath: '/usluge'
      preLoaderRoute: typeof UslugeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertoar': {
      id: '/repertoar'
      path: '/repertoar'
      fullPath: '/repertoar'
      preLoaderRoute: typeof RepertoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nacin-rada': {
      id: '/nacin-rada'
      path: '/nacin-rada'
      fullPath: '/nacin-rada'
      preLoaderRoute: typeof NacinRadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvala': {
      id: '/hvala'
      path: '/hvala'
      fullPath: '/hvala'
      preLoaderRoute: typeof HvalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dostupni-termini': {
      id: '/dostupni-termini'
      path: '/dostupni-termini'
      fullPath: '/dostupni-termini'
      preLoaderRoute: typeof DostupniTerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dopunski-programi': {
      id: '/dopunski-programi'
      path: '/dopunski-programi'
      fullPath: '/dopunski-programi'
      preLoaderRoute: typeof DopunskiProgramiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upit/svadba': {
      id: '/upit/svadba'
      path: '/upit/svadba'
      fullPath: '/upit/svadba'
      preLoaderRoute: typeof UpitSvadbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upit/rodjendan-jubilej': {
      id: '/upit/rodjendan-jubilej'
      path: '/upit/rodjendan-jubilej'
      fullPath: '/upit/rodjendan-jubilej'
      preLoaderRoute: typeof UpitRodjendanJubilejRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upit/korporativna-proslava': {
      id: '/upit/korporativna-proslava'
      path: '/upit/korporativna-proslava'
      fullPath: '/upit/korporativna-proslava'
      preLoaderRoute: typeof UpitKorporativnaProslavaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upit/klupska-svirka': {
      id: '/upit/klupska-svirka'
      path: '/upit/klupska-svirka'
      fullPath: '/upit/klupska-svirka'
      preLoaderRoute: typeof UpitKlupskaSvirkaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DopunskiProgramiRoute: DopunskiProgramiRoute,
  DostupniTerminiRoute: DostupniTerminiRoute,
  FaqRoute: FaqRoute,
  HvalaRoute: HvalaRoute,
  InstagramRoute: InstagramRoute,
  KontaktRoute: KontaktRoute,
  NacinRadaRoute: NacinRadaRoute,
  RepertoarRoute: RepertoarRoute,
  UslugeRoute: UslugeRoute,
  UpitKlupskaSvirkaRoute: UpitKlupskaSvirkaRoute,
  UpitKorporativnaProslavaRoute: UpitKorporativnaProslavaRoute,
  UpitRodjendanJubilejRoute: UpitRodjendanJubilejRoute,
  UpitSvadbaRoute: UpitSvadbaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
